# Generated by Django 2.2.7 on 2019-12-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Rol'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['age'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuario'},
        ),
    ]
